on: [push, pull_request]
name: ci
jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-20.04 # 22.04 doesn't contain mlton
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mlton lua5.3 luajit
      - name: Build
        run: make
      - name: Test
        run: make test test-stackless-handle test-luajit test-nodejs test-nodejs-cps
      - name: Prepare third-party libraries
        run: make -C thirdparty install
      - name: Compile myself (Lua)
        run: ./lunarml LunarML.mlb
      - name: Compile myself (JavaScript)
        run: ./lunarml --js-cps LunarML.mlb
